---
- hosts: localhost
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: creating multiple files in master server
      file:
        path: '{{item}}'
        state: touch
      with_items:
        - devops1
        - devops2
        - devops3
