---
- hosts: test
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: install httpd
      command: yum install httpd -y

    - name: restart httpd
      service: name=httpd state=restarted

    - name: create a file in html directory
      file:
        path: "/var/www/html/index.html"
        state: touch

    - name: insert data into file
      copy:
           dest: "/var/www/html/index.html"
           content: |
             <h1> httpd installed in test server </h1>
             <h2> restarted it as well </h2>                                                                                                                      1,1           Top
